import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from '@mui/material-nextjs/v15-appRouter';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <meta property="og:title" content="Wallan Tuntemattomat" />
      <meta property="og:image" content="https://www.wallantuntemattomat.fi/logo.jpg" />
      <meta property="og:description" content="Wallan Tuntemattomat on vuonna 2012 alkunsa saanut satakuntalainen iskelmä ja bilemusaa soittava kahden miehen orkesteri" />
      <head>
        <title>Wallan Tuntemattomat</title>
      </head>
      <body style={{backgroundColor: "black", color: "white", fontFamily: "Tahoma, Helvetica, sans-serif"}}>
        <AppRouterCacheProvider>
        {children}
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
